Repository TEAM-PLAYTOGETHER/PlayTogether_iOS, pull requests merged in 2022-10, with the labels that each got.

#77 [Feat] 채팅 구현
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlayTogether/PlayTogether/Application/AppDelegate.swift
  PlayTogether/PlayTogether/Application/TabBar/TabBarController.swift
  PlayTogether/PlayTogether/Extensions/UIImage+Extension.swift
  PlayTogether/PlayTogether/Extensions/UITableViewCell+Extension.swift
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendActiveIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendActiveIcon.imageset/btn_send_active.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendActiveIcon.imageset/btn_send_active@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendActiveIcon.imageset/btn_send_active@3x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendInActiveIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendInActiveIcon.imageset/btn_send_inactive.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendInActiveIcon.imageset/btn_send_inactive@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/Chatting/sendInActiveIcon.imageset/btn_send_inactive@3x.png
  PlayTogether/PlayTogether/Sources/Chat/ChatViewController.swift
  PlayTogether/PlayTogether/Sources/Chatting/Cell/ChattingListTableViewCell.swift
  PlayTogether/PlayTogether/Sources/Chatting/Cell/ChattingRoomTableViewCell.swift
  PlayTogether/PlayTogether/Sources/Chatting/Model/MessageDataModel.swift
  PlayTogether/PlayTogether/Sources/Chatting/Model/RoomDataModel.swift
  PlayTogether/PlayTogether/Sources/Chatting/Network/ChattingRoomListResponse.swift
  PlayTogether/PlayTogether/Sources/Chatting/Network/ChattingService.swift
  PlayTogether/PlayTogether/Sources/Chatting/Network/MessageListResponse.swift
  PlayTogether/PlayTogether/Sources/Chatting/View/ChattingListViewController.swift
  PlayTogether/PlayTogether/Sources/Chatting/View/ChattingRoomViewController.swift
  PlayTogether/PlayTogether/Sources/Chatting/ViewModel/ChattingListViewModel.swift
  PlayTogether/PlayTogether/Sources/Chatting/ViewModel/ChattingRoomViewModel.swift
  PlayTogether/PlayTogether/Sources/Common/APIConstants.swift
  PlayTogether/PlayTogether/Sources/Common/PaddingLabel.swift
  PlayTogether/PlayTogether/Sources/Common/SocketIOManger.swift
  PlayTogether/PlayTogether/Sources/MyPage/View/MyPageSubwayLabelView.swift
Labels: Feat, Add

#106 [Feat] 먹갈할 리스트 서버 연동 및 상세 뷰 연결, 번개 리스트 페이지네이션 및 엠티 뷰 구현
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether/Sources/Common/APIConstants.swift
  PlayTogether/PlayTogether/Sources/Home/Network/ThunListService.swift
  PlayTogether/PlayTogether/Sources/Home/View/DoThunListViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/EatThunListViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/GoThunListViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/HomeViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/ThunListViewController.swift
  PlayTogether/PlayTogether/Sources/Home/ViewModel/DoThunListViewModel.swift
  PlayTogether/PlayTogether/Sources/Home/ViewModel/EatThunListViewModel.swift
  PlayTogether/PlayTogether/Sources/Home/ViewModel/GoThunListViewModel.swift
  PlayTogether/PlayTogether/Sources/Thun/Network/ThunService.swift
  PlayTogether/PlayTogether/Sources/Thun/View/LikedDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/LikedThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/OpenedDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/OpenedThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/SubmittedDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/SubmittedThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/ThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/ViewModel/LikedThunViewModel.swift
  PlayTogether/PlayTogether/Sources/Thun/ViewModel/OpenedThunViewModel.swift
  PlayTogether/PlayTogether/Sources/Thun/ViewModel/SubmittedThunViewModel.swift
  PlayTogether/PlayTogether/Sources/Thun/ViewModel/ThunViewModel.swift
Labels: Feat, Fix, Incomplete

#108 [Feat] 상대방 정보 뷰 UI구현
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlayTogether/PlayTogether/Sources/Thun/View/CheckMemberInfoViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/SubmittedDetailThunViewController.swift
Labels: Feat, Incomplete

#111 [Feat] 로티 애니메이션 로직 수정
  PlayTogether/PlayTogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlayTogether/PlayTogether/Sources/Home/View/HomeViewController.swift
Labels: Feat

#113 [Feat] Splash Image 추가 및 Launch Screen 구성
  PlayTogether/PlayTogether/Resources/Assets.xcassets/splashIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/splashIcon.imageset/Rectangle.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/splashIcon.imageset/Rectangle@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/splashIcon.imageset/Rectangle@3x.png
  PlayTogether/PlayTogether/Resources/Base.lproj/LaunchScreen.storyboard
Labels: Feat, Add
