Repository TEAM-PLAYTOGETHER/PlayTogether_iOS, pull requests merged in 2022-09, with the labels that each got.

#65 [Feat] 온보딩 동아리 개설 뷰 수정
  PlayTogether/PlayTogether/Sources/Onboarding/ViewController/CreateMeetViewController.swift
  PlayTogether/PlayTogether/Sources/Onboarding/ViewModel/CreateMeetViewModel.swift
Labels: Feat

#73 [Feat] 번개 신청 완료 뷰 서버 연동
  PlayTogether/PlayTogether/Sources/Home/Network/HomeResponse.swift
  PlayTogether/PlayTogether/Sources/Home/View/CompleteThunViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/EnterDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/HomeViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/Network/DetailThunResponse.swift
  PlayTogether/PlayTogether/Sources/Thun/ViewModel/DetailThunViewModel.swift
Labels: Feat

#74 [Feat] 번개 생성 완료 뷰 서버 연동
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether/Sources/Home/Network/CreateThunResponse.swift
  PlayTogether/PlayTogether/Sources/Home/Network/HomeResponse.swift
  PlayTogether/PlayTogether/Sources/Home/View/CompleteThunViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/CreateThunViewController.swift
  PlayTogether/PlayTogether/Sources/Home/View/EnterDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Home/ViewModel/CreateThunViewModel.swift
Labels: Feat

#80 [Feat] 이용약관 뷰 구현
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlayTogether/PlayTogether/Application/AppDelegate.swift
  PlayTogether/PlayTogether/Application/SceneDelegate.swift
  PlayTogether/PlayTogether/Extensions/UIButton+Extension.swift
  PlayTogether/PlayTogether/Extensions/UIColor+Extension.swift
  PlayTogether/PlayTogether/Extensions/UIImage+Extension.swift
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkActiveIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkActiveIcon.imageset/icn_check_active.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkActiveIcon.imageset/icn_check_active@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkActiveIcon.imageset/icn_check_active@3x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkInActiveIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkInActiveIcon.imageset/icn_check_inactive.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkInActiveIcon.imageset/icn_check_inactive@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/CheckIcon/checkInActiveIcon.imageset/icn_check_inactive@3x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/appleIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/appleIcon.imageset/Logo - SIWA - Left-aligned - White - Large 1.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/appleIcon.imageset/Logo - SIWA - Left-aligned - White - Large 1@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/appleIcon.imageset/Logo - SIWA - Left-aligned - White - Large 1@3x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/kakaoIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/kakaoIcon.imageset/icon_kakao.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/kakaoIcon.imageset/icon_kakao@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/LoginIcon/kakaoIcon.imageset/icon_kakao@3x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/loginCenterIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/loginCenterIcon.imageset/Frame 117.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/loginCenterIcon.imageset/Frame 117@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/loginCenterIcon.imageset/Frame 117@3x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/selectedIcon.imageset/Contents.json
  PlayTogether/PlayTogether/Resources/Assets.xcassets/selectedIcon.imageset/icn_select.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/selectedIcon.imageset/icn_select@2x.png
  PlayTogether/PlayTogether/Resources/Assets.xcassets/selectedIcon.imageset/icn_select@3x.png
  PlayTogether/PlayTogether/Resources/Info.plist
  PlayTogether/PlayTogether/Sources/LogIn/Controller/LogInViewController.swift
  PlayTogether/PlayTogether/Sources/LogIn/View/LoginButtonView.swift
  PlayTogether/PlayTogether/Sources/Onboarding/Network/FetchMeetingService.swift
  PlayTogether/PlayTogether/Sources/Onboarding/View/ChoiceCell.swift
  PlayTogether/PlayTogether/Sources/Onboarding/ViewController/OnboardingViewController.swift
  PlayTogether/PlayTogether/Sources/Onboarding/ViewController/ReDownloadViewController.swift
  PlayTogether/PlayTogether/Sources/TermsService/Controller/CheckTermsServiceViewController.swift
  PlayTogether/PlayTogether/Sources/TermsService/View/CheckTermsView.swift
  PlayTogether/PlayTogether/Sources/TermsService/ViewModel/CheckTermsServiceViewModel.swift
Labels: Feat, Add

#89 [Feat] 터치 관련 프로토콜 세분화
  PlayTogether/PlayTogether/Sources/Common/PopUpViewController.swift
Labels: Feat

#86 [Feat] 온보딩 이동 로직 및 수정 사항 변경
  PlayTogether/PlayTogether/Sources/Common/APIConstants.swift
  PlayTogether/PlayTogether/Sources/Onboarding/Network/SelfIntroduceService.swift
  PlayTogether/PlayTogether/Sources/Onboarding/ViewController/CreateMeetViewController.swift
  PlayTogether/PlayTogether/Sources/Onboarding/ViewController/OnboardingViewController.swift
  PlayTogether/PlayTogether/Sources/Onboarding/ViewController/SelfIntroduceViewController.swift
  PlayTogether/PlayTogether/Sources/Onboarding/ViewModel/SelfIntroduceViewModel.swift
Labels: Feat, Del

#91 [Feat] 팝업 뷰 터치 관련 프로토콜 수정사항 반영
  PlayTogether/PlayTogether/Sources/Home/View/EnterDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/OpenedDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/SubmittedDetailThunViewController.swift
Labels: Feat, Fix

#93 [Feat] 내가 신청한 번개에 있는 취소 버튼 분기처리
  PlayTogether/PlayTogether/Sources/Common/APIConstants.swift
  PlayTogether/PlayTogether/Sources/Home/ViewModel/ExistThunViewModel.swift
  PlayTogether/PlayTogether/Sources/Thun/View/SubmittedDetailThunViewController.swift
Labels: Feat, Fix

#83 [Feat] 홈 탭 새로고침 및 바텀시트 구현
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlayTogether/PlayTogether.xcodeproj/xcshareddata/xcschemes/PlayTogether.xcscheme
  PlayTogether/PlayTogether/Resources/HomeRefreshLottie.json
  PlayTogether/PlayTogether/Sources/Common/APIConstants.swift
  PlayTogether/PlayTogether/Sources/Common/BottomSheetView/BottomSheetTableViewCell.swift
  PlayTogether/PlayTogether/Sources/Common/BottomSheetView/BottomSheetViewController.swift
  PlayTogether/PlayTogether/Sources/Home/Network/CrewListResponse.swift
  PlayTogether/PlayTogether/Sources/Home/Network/HomeService.swift
  PlayTogether/PlayTogether/Sources/Home/View/HomeViewController.swift
  PlayTogether/PlayTogether/Sources/Home/ViewModel/HomeViewModel.swift
  PlayTogether/PlayTogether/Utils/CompleteURLLoggerPlugin.swift
Labels: Feat, Add

#99 [Feat] 게시글 신고하기 뷰, 게시글 신고 완료 뷰 UI구현 및 서버연동
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlayTogether/PlayTogether/Sources/Common/APIConstants.swift
  PlayTogether/PlayTogether/Sources/Home/View/EnterDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Home/ViewModel/ExistThunViewModel.swift
  PlayTogether/PlayTogether/Sources/Thun/Network/ReportThunService.swift
  PlayTogether/PlayTogether/Sources/Thun/View/LikedDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/ReportCompleteThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/ReportThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/SubmittedDetailThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/View/ThunViewController.swift
  PlayTogether/PlayTogether/Sources/Thun/ViewModel/CancelThunViewModel.swift
Labels: Feat, Add

#100 [Feat] FCM Token 추출 및 로그인 API 연동
  PlayTogether/PlayTogether.xcodeproj/project.pbxproj
  PlayTogether/PlayTogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PlayTogether/PlayTogether/Application/AppDelegate.swift
  PlayTogether/PlayTogether/Extensions/UIImage+Extension.swift
  PlayTogether/PlayTogether/PlayTogether.entitlements
  PlayTogether/PlayTogether/Resources/GoogleService-Info.plist
  PlayTogether/PlayTogether/Resources/Info.plist
  PlayTogether/PlayTogether/Sources/Common/APIConstants.swift
  PlayTogether/PlayTogether/Sources/Common/BirthYearPickerViewController.swift
  PlayTogether/PlayTogether/Sources/LogIn/Controller/LogInViewController.swift
  PlayTogether/PlayTogether/Sources/LogIn/Network/LoginResponse.swift
  PlayTogether/PlayTogether/Sources/LogIn/Network/LoginService.swift
  PlayTogether/PlayTogether/Sources/LogIn/ViewModel/LoginViewModel.swift
Labels: Feat, Add

#104 [Feat] UIPickerView 코드 개선
  PlayTogether/PlayTogether/Sources/TermsService/Controller/InputGenderBirthYearViewController.swift
Labels: Feat, Del
